import scanpy as sc

ad_all = sc.read('data/WangXin20214SciAdv/Wang_Glioma.h5ad')
#date generated by converted from Wang et al Science advance
#https://www.science.org/doi/10.1126/sciadv.adn4306


ad = ad_all[~ad_all.obs['patient'].isin(['RM05']),:] #removed the obnormal patient as indicated by the authors
gbm = ad[ad.obs['celltype'].isin(['GBM cell']),:]


sc.pl.dotplot(gbm, var_names = ['NTRK2','KCNH5','SHANK2',
'TTYH2','CNTN1','CNTN2','CNTN3','CACNA1A','CACNA1B','CACNA1C','CACNA1D',
'CACNA1E','CACNA2D1','CACNA2D3',
'GRIN2A','GRIN2B','GRM1','GRM5','GRM7',], groupby = 'type', swap_axes = True,standard_scale = 'var',
 cmap ='Blues',vmax = 1.25)

